os: osx
language: rust
rust:
  - 1.34.2
cache: cargo
env:
  global:
    - RELEASE_TARGETS="osx"
    - RELEASE_VERSION="cargo"
    - RELEASE_FILE_PREFIX="Stabman-"
    - RELEASE_RUST_VERSION="1.34.2"
    - RELEASE_FEATURES="debug,controller"
    - RELEASE_WITH_CONTROLLER="0"
    - RELEASE_PRINT_CARGO_STDERR="1"
before_install:
  - brew install SDL2
script:
  - bin/build-release
